language: node_js
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_8684fc738fed_key -iv $encrypted_8684fc738fed_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'gaoxingyun'
- git config --global user.email 'xingyungao@hotmail.com'

before_script:
- echo "before_script"
install:
- npm install -g hexo
- npm install -g hexo-cli
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
