language: node_js
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_8684fc738fed_key -iv $encrypted_8684fc738fed_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name 'gaoxingyun'
- git config --global user.email 'xingyungao@hotmail.com'
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
