language: node_js
branches:
  only:
  - master
# cache:
#   directories:
#   - node_modules
before_install:
- nvm install v10.0.0
- nvm use v10.0.0
- node -v
- npm -v
- openssl aes-256-cbc -K $encrypted_8684fc738fed_key -iv $encrypted_8684fc738fed_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

before_script:


# 免密码登陆ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'gaoxingyun'
- git config --global user.email 'xingyungao@hotmail.com'

# 修改时区
- export TZ=Asia/Shanghai

install:
- npm install -g hexo-cli
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy

# 杀掉ssh-agent进程
- ssh-agent -k
